const KAKAO_SCOPE_NICKNAME = "profile_nickname";
const KAKAO_SCOPE_PROFILE_IMAGE = "profile_image";
const KAKAO_SCOPE_GENDER = "gender";
const KAKAO_SCOPE_BIRTHDAY = "birthday";

const URL_PERSONAL_AGREEMENT =
  "https://tightee.notion.site/a1b5cc0997014242a057b74025c3d997";

export {
  KAKAO_SCOPE_NICKNAME,
  KAKAO_SCOPE_PROFILE_IMAGE,
  KAKAO_SCOPE_GENDER,
  KAKAO_SCOPE_BIRTHDAY,
  URL_PERSONAL_AGREEMENT,
};
